[build]
  command = "npm install --legacy-peer-deps && ng build"
  publish = "dist/nestify-web"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
